name: DeltalakePolarsDemo

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.2.2
    - name: Install poetry
      run: pipx install poetry
    - name: Set up Python 3.10
      uses: actions/setup-python@v5.6.0
      with:
        python-version: "3.10"
        cache: 'poetry'
    - name: Configure poetry
      run: |
        poetry config virtualenvs.in-project true
    - name: Install dependencies
      run: |
        poetry install
    - name: Lint with ruff
      run: |
        poetry run ruff .
